"""Add UserMention table for individual mentions

Revision ID: 27d7fcc4f835
Revises: d0b93c424e4a
Create Date: 2025-10-04 14:17:28.297480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d7fcc4f835'
down_revision: Union[str, Sequence[str], None] = 'd0b93c424e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('author_name', sa.String(), nullable=True),
    sa.Column('author_avatar_url', sa.String(), nullable=True),
    sa.Column('author_profile_url', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('original_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_processed', sa.String(), nullable=True),
    sa.Column('keywords_matched', sa.JSON(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('response_suggested', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['reputation_analyses.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_mentions_analysis_id'), 'user_mentions', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_user_mentions_external_id'), 'user_mentions', ['external_id'], unique=False)
    op.create_index(op.f('ix_user_mentions_id'), 'user_mentions', ['id'], unique=False)
    op.create_index(op.f('ix_user_mentions_intent'), 'user_mentions', ['intent'], unique=False)
    op.create_index(op.f('ix_user_mentions_platform'), 'user_mentions', ['platform'], unique=False)
    op.create_index(op.f('ix_user_mentions_priority'), 'user_mentions', ['priority'], unique=False)
    op.create_index(op.f('ix_user_mentions_product_id'), 'user_mentions', ['product_id'], unique=False)
    op.create_index(op.f('ix_user_mentions_sentiment'), 'user_mentions', ['sentiment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_mentions_sentiment'), table_name='user_mentions')
    op.drop_index(op.f('ix_user_mentions_product_id'), table_name='user_mentions')
    op.drop_index(op.f('ix_user_mentions_priority'), table_name='user_mentions')
    op.drop_index(op.f('ix_user_mentions_platform'), table_name='user_mentions')
    op.drop_index(op.f('ix_user_mentions_intent'), table_name='user_mentions')
    op.drop_index(op.f('ix_user_mentions_id'), table_name='user_mentions')
    op.drop_index(op.f('ix_user_mentions_external_id'), table_name='user_mentions')
    op.drop_index(op.f('ix_user_mentions_analysis_id'), table_name='user_mentions')
    op.drop_table('user_mentions')
    # ### end Alembic commands ###
