"""add_is_marked_field_to_user_mentions

Revision ID: 851354068e8d
Revises: 27d7fcc4f835
Create Date: 2025-10-04 16:29:15.460862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851354068e8d'
down_revision: Union[str, Sequence[str], None] = '27d7fcc4f835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists, if not add it
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = inspector.get_columns('user_mentions')
    column_names = [c['name'] for c in columns]
    
    if 'is_marked' not in column_names:
        op.add_column('user_mentions', sa.Column('is_marked', sa.Boolean(), nullable=True, default=False))
    
    # Update all existing rows to have False value
    op.execute("UPDATE user_mentions SET is_marked = 0 WHERE is_marked IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_mentions', 'is_marked')
    # ### end Alembic commands ###
