"""Add enhanced analysis fields

Revision ID: d0b93c424e4a
Revises: 
Create Date: 2025-10-04 12:49:43.602576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b93c424e4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('app_store_url', sa.String(), nullable=True),
    sa.Column('google_play_url', sa.String(), nullable=True),
    sa.Column('brand_keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('reputation_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('serp_results', sa.JSON(), nullable=True),
    sa.Column('app_store_reviews', sa.JSON(), nullable=True),
    sa.Column('google_play_reviews', sa.JSON(), nullable=True),
    sa.Column('key_insights', sa.JSON(), nullable=True),
    sa.Column('issues_list', sa.JSON(), nullable=True),
    sa.Column('intent_breakdown', sa.JSON(), nullable=True),
    sa.Column('crisis_analysis', sa.JSON(), nullable=True),
    sa.Column('response_drafts', sa.JSON(), nullable=True),
    sa.Column('data_citations', sa.JSON(), nullable=True),
    sa.Column('actionable_insights', sa.JSON(), nullable=True),
    sa.Column('evidence_data', sa.JSON(), nullable=True),
    sa.Column('analysis_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reputation_analyses_id'), 'reputation_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_reputation_analyses_product_id'), 'reputation_analyses', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reputation_analyses_product_id'), table_name='reputation_analyses')
    op.drop_index(op.f('ix_reputation_analyses_id'), table_name='reputation_analyses')
    op.drop_table('reputation_analyses')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
